"""Emit the paper-number -> command -> frozen-entry map.

Generated from the frozen table rather than written by hand: a hand-kept map
drifts the moment an entry is added, and this one exists precisely so a
reader can check a number without trusting prose.

    PYTHONPATH=. .venv/bin/python run_numbers_map.py --out ../artifact/NUMBERS.md
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger("run_numbers_map")

# Which runner writes each source file.  Verified by locating the filename in
# the runner that constructs it, not by naming convention.
PRODUCER: Dict[str, str] = {
    "analysis.json":
        "PYTHONPATH=. uv run python run_analyze.py out/corpus_v2",
    "crosscheck.json":
        "PYTHONPATH=. uv run python run_crosscheck.py",
    "fit_interleaved.json":
        "PYTHONPATH=. uv run python run_fit.py --corpus out/corpus_v2",
    "pcurve_interleaved.json":
        "PYTHONPATH=. uv run python run_pcurve.py --corpus out/corpus_v2",
    "selection.json":
        "PYTHONPATH=. uv run python run_selection.py --corpus out/corpus_v2",
    "costbench.json":
        "PYTHONPATH=. uv run python run_costbench.py",
    "crossover.json":
        "PYTHONPATH=. uv run python run_crossover.py",
    "model_comparison.json":
        "PYTHONPATH=. uv run python run_modelcmp.py "
        "--a out/corpus_v2 --b out/corpus_qwen3vl",
    "policy_analysis.json":
        "PYTHONPATH=. uv run python run_analyze_policies.py "
        "out/policies_v3 --group feasible",
    "seed_comparison.json":
        "PYTHONPATH=. uv run python run_seedcmp.py "
        "out/corpus_v2 out/corpus_s43 out/corpus_s44",
    "summary.json":
        "PYTHONPATH=. uv run python run_temporal_analyze.py out/temporal_v2",
    "base_state.json":
        "(raw archived input; consumed, not produced)",
}

TIMING_SOURCES = {"costbench.json", "crossover.json", "pcurve_interleaved.json"}

HEADER = """# Paper number -> command -> frozen entry

Generated by `run_numbers_map.py` from `paper/numbers.json`. Do not edit by
hand; regenerate instead.

Every quantity the paper reports is here with the exact denominator it is
defined over. Conditional rates in this evaluation differ mainly in their
denominator, and the frozen table exists so two of them cannot be
interchanged --- read the denominator column before quoting a value.

**Rescoring entries are deterministic.** Identical code over identical
archived generations reproduces every count exactly.

**Timing entries are not, and should not be.** Absolute verification times
moved by up to a third between two sweeps on the same machine. Reproduce the
ordering, not the milliseconds. Timing-derived entries are marked (T).
"""


def build(frozen: Path) -> str:
    data = json.loads(frozen.read_text())
    entries = data["entries"]
    by_source: Dict[str, List[dict]] = {}
    for e in entries:
        by_source.setdefault(e.get("source") or "(derived in the table)",
                             []).append(e)

    out = [HEADER, f"\n{len(entries)} entries across "
                   f"{len(by_source)} sources.\n"]
    for source in sorted(by_source):
        base = Path(source).name
        cmd = PRODUCER.get(base, "(see the table's own source field)")
        timing = " **(T)**" if base in TIMING_SOURCES else ""
        out.append(f"\n## `{source}`{timing}\n")
        out.append(f"```bash\ncd pilot && {cmd}\n```\n")
        out.append("| Entry | Value | k/n | 95% CI | Denominator |")
        out.append("|---|---|---|---|---|")
        for e in sorted(by_source[source], key=lambda x: x["name"]):
            v = e["value"]
            v = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
            kn = (f"{e['k']}/{e['n']}" if e.get("k") is not None
                  else (str(e["n"]) if e.get("n") is not None else ""))
            den = (e.get("denominator") or "").replace("|", "/")
            out.append(f"| `{e['name']}` | {v} | {kn} | "
                       f"{e.get('ci95') or ''} | {den} |")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--frozen", default="../paper/numbers.json")
    p.add_argument("--out", default="../artifact/NUMBERS.md")
    args = p.parse_args(argv)
    logging.basicConfig(level=logging.INFO, stream=sys.stdout,
                        format="%(levelname)-7s %(message)s")

    frozen = Path(args.frozen)
    if not frozen.exists():
        logger.error("frozen table not found: %s", frozen)
        return 1
    text = build(frozen)
    dest = Path(args.out)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text)
    logger.info("wrote %s (%d bytes)", dest, len(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
